name: Release

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  issues: write

jobs:
  semantic-versionning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

  publish-image:
    needs: semantic-versionning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Log in to gcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GCR_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Get latest tag
        id: get-tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV


      - name: Build Docker image
        run: |
          docker build -t ghcr.io/eni-devops-project/frontend:${TAG} .
          docker tag ghcr.io/eni-devops-project/frontend:${TAG} ghcr.io/eni-devops-project/frontend:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/eni-devops-project/frontend:${TAG}
          docker push ghcr.io/eni-devops-project/frontend:latest
