name: Publish container image

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to gcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/eni-devops-project/frontend:$GITHUB_REF_NAME .
          docker tag ghcr.io/eni-devops-project/frontend:$GITHUB_REF_NAME ghcr.io/eni-devops-project/frontend:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/eni-devops-project/frontend:$GITHUB_REF_NAME
          docker push ghcr.io/eni-devops-project/frontend:latest
